### ISSUE TITLE
Problem of BAMHandler and FOS

### ISSUE THREAD

**Issue by takatsugukosugi** [jpiper/pyDNase#11]
Hi!
I used pyDNase ver.0.1.7.
I think pyDNase have a few problem.
First,  BAMHandler. 
Second, How to Calculate FOS.

BAMHandler
---
along with Introduction, I commanded
```
import pyDNase
reads = pyDNase.BAMHandler(pyDNase.example_reads())
reads["chr6,170863500,170863532,+"]
```
then
```
{'+': array([0,0,0,1,0,0,1,1,2,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,1,0,0,0,1]),
 '-': array([0,10,1,0,1,0,4,9,0,1,0,2,1,0,0,0,0,0,3,0,6,3,0,0,0,1,1,1,3,0,3,6])}
```
I confirmed example.bam, so I think it may be wrong. I think "chr6,170863500,170863532,+" means "BED" format, so  I think that "+" array is off the +1bp and "-" array is off the -1bp. I think expected return is this, so can you confirm? 
```
{'+': array([0,0,0,0,1,0,0,1,1,2,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,1,0,0,0]),
 '-': array([10,1,0,1,0,4,9,0,1,0,2,1,0,0,0,0,0,3,0,6,3,0,0,0,1,1,1,3,0,3,6,0])}
```

How to Calculate FOS
---
```
leftReads   = float(sum(cutArray[:bgsize]))
centreReads = float(sum(cutArray[bgsize:-bgsize]))
rightReads  = float(sum(cutArray[-bgsize:]))
    try:
        return ( (centreReads+1) / leftReads ) + ( (centreReads+1)/rightReads)
``` 
This code is function of FOS in pyDNase
I read Neph et al. 2012 (Nature), I think that we should calculate of the average of leftReads, centreReads, and rightReads. but function of FOS don't calculate of the average. 
Additionally, they wrote central component (6–40 nucleotides) and flanking component (3–10 nucleotides), so central component is dependent of bed file that we have. so, that is OK, but  default of bgsize is 35. I think it is too large. What do you think about that.

**Comment by jpiper** [comment]
Well that's certainly worrying! I can confirm from this end on a clean virtualenvironment that the output behaves as it should.

```
Python 2.7.9 (default, May  4 2015, 14:39:12) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyDNase
>>> reads = pyDNase.BAMHandler(pyDNase.example_reads())
>>> reads["chr6,170863500,170863532,+"]
{'+': array([0, 0, 0, 1, 0, 0, 1, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1]), '-': array([ 0, 10,  1,  0,  1,  0,  4,  9,  0,  1,  0,  2,  1,  0,  0,  0,  0,
        0,  3,  0,  6,  3,  0,  0,  0,  1,  1,  1,  3,  0,  3,  6])}
```

What python interpreter and version are you using? What OS? Can you create a new virtual environment and install pyDNase from scratch and see if this still persists? I worry this is a problem with outdated packages.

With regards to the FOS, this isn't a perfect implementation, as the only time it is ever used in the code the central and flanking regions are always the same size (dnase_to_treeview), so taking the average would just be a constant scaling of the values. I will go ahead and put this on my todo list to fix. If you want to make a pull request, that would also be fine :)

The real FOS also does MLE to determine the flanking regions and the central component, and we're not doing this here. In actuality this is purely for sorting the regions for the heatmap viewing.

Personally I don't think the FOS is a good metric for identifying footprints, and having a central component larger than the flanking one has a propensity to identify footprints flanked by 'spikes' which are effectively artefacts in the data. Parameters will always be argues over though!

**Comment by jpiper** [comment]
Oh, I misread your comment! Where you place the DNase cuts is a matter of choice really, as the cuts happen at the phosphodiester backbone in between bases and there's no standard way of representing this. You can either say the DNase cut happened at the 5' most end of the read, or the next basepair over. In reality the DNase cut happened in between, and there's no right or wrong here.
