### ISSUE TITLE
dnase_bias_estimator.py argument names

### ISSUE THREAD

**Issue by drew-hughes** [jpiper/pyDNase#12]
Hi Jason,

Thanks for putting together these excellent tools and making them so accessible. I've just downloaded pyDNase. When attempting to run dnase_bias_estimator.py I get a "namespace has no attribute genomesize" error. I believe the argument variable name is stored as "genomesize" (line 89) and then referred to as "genome_size" (line 96).

Best,

Drew

**Comment by jpiper** [comment]
Thanks for this! Fixing in #17
