### ISSUE TITLE
instructions for disabling -fdrlimit with Wellinton are contradictory, don't agree with source code

### ISSUE THREAD

**Issue by bheavner** [jpiper/pyDNase#13]
The FAQ at https://github.com/jpiper/pyDNase/blob/84ff43412752191b89218565cdab3eb3286ca2cf/docs/faqs.rst say "if you have low read depths you might need to adjust the -fdrlimit parameter to something less stringent like "-10" or "-5", which sets the mimimum amounts of evidence required to support the alternate hypothesis of there being a footprint. You can set this to 0 if you want to disable this feature altogether,"

However, the tutorial at https://github.com/jpiper/pyDNase/blob/84ff43412752191b89218565cdab3eb3286ca2cf/docs/tutorial.rst says "You can set -fdrlimit to -0.01 if you want to disable this feature altogether, "

Meanwhile, the source code at line 33 of https://github.com/jpiper/pyDNase/blob/241657206fdb43929a1c1648940554bae8b95d52/pyDNase/scripts/wellington_footprints.py says "default=-20,type=int)

Since it's an int, that suggests I can't set the limit to -0.01; and I get an error stating it must be less than 0 if I set it to -0...

**Comment by jpiper** [comment]
Thanks for the bug report! You're right on both counts.

a) This shouldn't be forced to `int` in the `argparse` - patching it to `float` will fix this issue
b) The `assert` should be `<= 0` rather than `< 0`

I'll work on patching this in

**Comment by bheavner** [comment]
Cool. Thanks for checking it out. I don't know where else fdrlimit is used in the code - is changing to a float risky (for example, floating point issues if there are there strict equality checks later)? Seems like the b) patch may be safer than the a) patch. Then the tutorial could be updated to also say set to 0 to disable...

**Comment by jpiper** [comment]
Ah yes, good point. I've implemented these fixes in af6c8e9867da341c1e85d842f9078e596dcabab1 and hopefully get this deployed later today

**Comment by jpiper** [comment]
Fixing in #17
