### ISSUE TITLE
For ATAC-seq bias correction, is an naked DNA sequencing data necessary?

### ISSUE THREAD

**Issue by Honchkrow** [jpiper/pyDNase#24]
Hello,
    Recently I use pyDNase to deal with my ATAC-seq data. I read the paper about Wellington-bootstrap, it is said that the bias is corrected using observed cuts and expected counts. I also read the paper about how to calculate the "predicted count". The "predicted count" can be from chromatin derived DNase-seq or naked DNA. Which method pyDNase support? Is an naked DNA sequencing data necessary?
    Thanks!

**Comment by jpiper** [comment]
Hi there, naked DNA sequencing isn't necessary. Data from [He. et al (2014)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4018771/) (Shirley Liu's lab) Naked DNA was used to determine DNase I cutting preference for all 6-mers, and this data is [here](https://github.com/jpiper/pyDNase/blob/master/pyDNase/data/IMR90_6mer.pickle)

However, for ATAC-seq data if you wanted to normalise against ATAC-seq insertion bias then you'd need a dataset to determine this from. A common method is to use all the cuts outside the peaks but the better method is to use Naked DNA for this.

You can look at [dnase_bias_estimator.py](https://github.com/jpiper/pyDNase/blob/master/pyDNase/scripts/dnase_bias_estimator.py) on how to calculate your own bias file, and then you use this fie in [dnase_average_profile.py](https://github.com/jpiper/pyDNase/blob/master/pyDNase/scripts/dnase_average_profile.py#L13) 
 or [dnase_to_javatreeview.py](https://github.com/jpiper/pyDNase/blob/master/pyDNase/scripts/dnase_to_javatreeview.py)with the "--bias-file" command.

If you [look in the code](https://github.com/jpiper/pyDNase/blob/master/pyDNase/__init__.py#L568), what is actually happening here is we're applying the formula developed in the original bias paper.

I never got around to correcting for bias during footprinting itself before I finished my PhD. I could look into doing this, though.

**Comment by A1dnoah** [comment]
Thanks for your reply!
