### ISSUE TITLE
error in wellington_footprints.py

### ISSUE THREAD

**Issue by billgreenwald** [jpiper/pyDNase#28]
Hi!  

I just downloaded wellington, and when running wellington_footprints.py I was getting the error:

```
error at line 85:
'<' is not defined for GenomicInterval objects
```

I determined this was happening only when a BED file with multiple chromosomes was passed.  The full line 85 was
```
orderedbychr = [item for sublist in sorted(regions.intervals.values()) for item in sorted(sublist, key=lambda peak: peak.startbp)]
```
but, after some testing, it seemed like the error was coming from
```
sorted(regions.intervals.values())
```

Based on the comment above that the goal is to iterate by chromosome, then position, I edited line 85 to be
```
orderedbychr = [item for sublist in sorted(regions.intervals.values(),key=lambda genomicIntervalList: genomicIntervalList[0].chromosome) for item in sorted(sublist, key=lambda peak: peak.startbp)]
```

This has overcome the bug and the program runs.  I am posting this to both confirm that this is the intended result and that my output should be correct, and to give a bugfix if so.

Thanks!

**Comment by dhb2128** [comment]
Hi,
I'm trying to run wellington_footprints.py as well and was encountering the same error. I checked quickly and it looks like your fix also prevented the error on some data I downloaded from encode `wellington_footprints.py -p $SLURM_NPROCS wgEncodeUwDgfHaspPk.bed wgEncodeUwDgfHaspAln.bam pydnase_out`, but I'd also like to know if the fix that Bill posted is correct.

Thanks!

**Comment by billgreenwald** [comment]
Hey @dhb2128, with my data, Wellington hangs with the last 80 threads finishing up and I get empty output.  Do your output files have entries in them?

**Comment by dhb2128** [comment]
I got the same message, "Waiting for the last 80 jobs to finish...", but it still produced a WellingtonFootprints.FDR.0.01.bed file, the WellingtonFootprints.wig file, and the files in the p value cutoff folder in the outdir.

**Comment by billgreenwald** [comment]
was your WellingtonFootprints.FDR.0.01.bed empty?

**Comment by dhb2128** [comment]
Not when I ran wellington_footprints.py. That one seemed to work. However, I get no output when I run wellington_bootstraps.py. Not sure if it's a threshold thing; self.scores is less than the FDR limit but `self.findDiffFP()` seems to not be returning any results.

Was it always empty for you, too?
