### ISSUE TITLE
example_footprint_scores.py

### ISSUE THREAD

**Issue by SaideepGona** [jpiper/pyDNase#32]
Hi. 
I can't seem to get the example_footprint_scores.py script running properly. I'm running Linux Mint and have passed the gcc --verison check. The error message I get is:
from: can't read /var/mail/pyDNase.footprinting
/home/saideep/anaconda3/bin/example_footprint_scores.py: line 6: syntax error near unexpected token `('
/home/saideep/anaconda3/bin/example_footprint_scores.py: line 6: `reads = pyDNase.BAMHandler(pyDNase.example_reads())'

Upon running I get a "crosshairs" cursor and when I click the error message pops up. Hopefully this is resolvable. Thanks!

**Comment by jpiper** [comment]
Hmm that's odd - what version of python are you running?

**Comment by SaideepGona** [comment]
Python 3.6.3

**Comment by SaideepGona** [comment]
Any idea on this yet?

**Comment by SaideepGona** [comment]
I think the issue has something to do with the example script setup. If I copy/paste the contents of the script into a new python file and run the new file as a normal scipt, it works correctly. I'm guessing the package itself is working properly even though the example script is a bit buggy.

**Comment by jpiper** [comment]
But I'm glad you got it running - apologies for the lack of support, this is my side-project now :)

**Comment by RaghadShu** [comment]
I am having the same issue.. Any idea why?
